global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'sentiment_analysis'
    static_configs:
      - targets: ['app:8000']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']